# Netlify configuration for Next.js 15 (App Router)
# Docs: https://docs.netlify.com/integrations/frameworks/next-js/

[build]
  command = "npm run build"
  publish = ".next"

[functions]
  node_bundler = "esbuild"
  external_node_modules = []

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
